- hosts: localhost
  connection: local
  tasks:
    - name: Criar VM no Ansible Lab
      azure_rm_devtestlabvirtualmachine:
        resource_group: clara-net-rg
        lab_name: clara-lab-ansible
        name: vm-ansible-lab
        notes: Olá, sou a VM desse ansible lab.
        os_type: linux
        vm_size: Standard_A2_v2
        user_name: dtladmin
        password: T1dogcp9!
        lab_subnet:
          virtual_network_name: rede-virtual-clara
          name: rede-virtual-claraSubnet
        disallow_public_ip_address: no
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          os_type: Linux
          version: latest