- hosts: localhost
  connection: local
  tasks:
    - name: Listar as fontes dos artefatos
      azure_rm_devtestlabartifactsource_facts:
        resource_group: clara-net-rg
        lab_name: clara-lab-ansible
      register: output
    - debug:
        var: output