- hosts: localhost
  connection: local
  tasks:
    - name: Listar os artefatos
      azure_rm_devtestlabartifact_facts:
        resource_group: clara-net-rg
        lab_name: clara-lab-ansible
        artifact_source_name: public repo
      register: output
    - debug:
        var: output