- hosts: localhost
  connection: local
  tasks:
    - name: Setando lab policie
      azure_rm_devtestlabpolicy:
        api_profile: latest
        resource_group: clara-net-rg
        lab_name: clara-lab-ansible
        policy_set_name: myDtlPolicySet
        name: myDtlPolicy
        fact_name: user_owned_lab_vm_count
        threshold: 5